paths:
  train_list: "/home/LifeSci/wenlab/hefengcs/VCD_torch_gnode05/data/data_div/total_moving2fixed/train_mid_1_NemoS.txt"
  val_list: "/home/LifeSci/wenlab/hefengcs/VCD_torch_gnode05/data/data_div/total_moving2fixed/val_mid_1_NemoS.txt"
training:
  batch_size: 1
  learning_rate: 1e-4
  max_epochs: 250
  devices: [1,3,5,7]
  accelerator: "gpu"
  strategy: "ddp_find_unused_parameters_true"
  #strategy: "ddp"
  log_every_n_steps: 50

callbacks:
  save_top_k: 1
  monitor: "val_loss"
  mode: "min"
  epoch_interval: 10

data_transforms:
  train_transform:
    - RandomHorizontalFlip: {p: 0.5}
    - RandomVerticalFlip: {p: 0.5}
    - RandomRotation: {p: 0.5}
    - RandomGaussianNoise: {p: 0.5}
    - RandomGaussianBlur: {p: 0.5}
    - RandomBrightness: {p: 0.5}
    - RandomContrast: {p: 0.5}
    - ToTensor: {}
  val_transform:
    - ToTensor: {}

experiment:
  model: "SwinIR_Timm"
  label: "Nemos_Compare_SwinIR_7.31"
  loss_config:
    psnr_loss:
      weight: 1.0      # 对应公式中的 psnr_loss/43
    ssim_loss:
      weight: 1.0526   # 计算为 1/0.95 的近似值
    edges_loss:
      weight: 10000.0  # 对应公式中的 edges_loss/1e-4
    multi_scale_mse:
      weight: 100000.0 # 对应公式中的 multi_scale_mse/1e-5
#    mip_loss:
#      weight: 1000.0   # 对应公式中的 MIP_loss_value/1e-3
    mse_loss:
      weight: 0.1      # 你手动定义的权重
#    PSF_flag: True

#    high_value_loss:
#      weight: 10000.0  # 对应公式中的 high_value_loss/1e-4
#    snr_loss:
#      weight: 0.0204   # 对应公式中的 1/49 的值

